spring:
  datasource:
     # url: jdbc:postgresql://192.168.18.27:5432/vehicle_track
      url: jdbc:postgresql://104.198.206.114:5432/vehicle_track
      username: postgres
      password: vtrack123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
